name: deploys

on:
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      HIFUMIN_API_URL: ${{ secrets.HIFUMIN_API_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: install
        run: pnpm -r i --frozen-lockfile && pnpm svelte-kit sync
      - name: cache
        uses: actions/cache@v3
        with:
          path: data
          key: hentai-cache-v2-${{ secrets.CACHE_HASH }}-${{ hashFiles('src/core/constants/codes/**/*.ts') }}
          restore-keys: |
            hentai-cache-v2-${{ secrets.CACHE_HASH }}-${{ hashFiles('src/core/constants/codes/**/*.ts') }}
            hentai-cache-v2-${{ secrets.CACHE_HASH }}-
      - name: fetch
        run: pnpm fetch:data
      - name: sync
        run: pnpm sync:data

  build:
    runs-on: ubuntu-latest
    needs: [fetch]
    env:
      APP_NAME: riffyh-runtime-private
      IMAGE_NAME: ghcr.io/rayriffy/riffyh-runtime-private
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: cache
        uses: actions/cache@v3
        with:
          path: data
          key: hentai-cache-v2-${{ secrets.CACHE_HASH }}-${{ hashFiles('src/core/constants/codes/**/*.ts') }}
          restore-keys: |
            hentai-cache-v2-${{ secrets.CACHE_HASH }}-${{ hashFiles('src/core/constants/codes/**/*.ts') }}
            hentai-cache-v2-${{ secrets.CACHE_HASH }}-
      - name: login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rayriffy
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: buildx
        uses: docker/setup-buildx-action@v2
      - name: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/rayriffy/riffyh-runtime
      - name: deploy
        uses: deploys-app/deploys-action@v1
        with:
          project: rayriffy
          location: gke.cluster-rcf2
          name: riffy-h
          image: ghcr.io/rayriffy/riffyh-runtime
          minReplicas: 1
          maxReplicas: 4
        env:
          DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
          DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
