name: runtime

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: rayriffy
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: qemu
        uses: docker/setup-qemu-action@v3
      - name: buildx
        uses: docker/setup-buildx-action@v3
      - name: build-and-push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/rayriffy/riffyh-core
